name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up dependencies (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update 
        sudo apt-get install -y libasio-dev zlib1g-dev libavformat-dev libavcodec-dev libavutil-dev libswscale-dev libswresample-dev libcurl4-gnutls-dev libspdlog-dev libfmt-dev

    - name: Set up dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: brew install asio ffmpeg spdlog

    - name: Create secrets.h
      run: cp secrets.example.h secrets.h

    - name: Build project
      run: |
        make all
        make -C monitor